INSERT INTO oys.sale_cartypecarmodel (car_model_id, transport_type_id) VALUES (1, 1);
INSERT INTO oys.sale_cartypecarmodel (car_model_id, transport_type_id) VALUES (3, 1);
INSERT INTO oys.sale_cartypecarmodel (car_model_id, transport_type_id) VALUES (4, 1);
INSERT INTO oys.sale_cartypecarmodel (car_model_id, transport_type_id) VALUES (5, 1);
INSERT INTO oys.sale_cartypecarmodel (car_model_id, transport_type_id) VALUES (6, 1);
INSERT INTO oys.sale_cartypecarmodel (car_model_id, transport_type_id) VALUES (7, 1);
INSERT INTO oys.sale_cartypecarmodel (car_model_id, transport_type_id) VALUES (8, 3);
INSERT INTO oys.sale_cartypecarmodel (car_model_id, transport_type_id) VALUES (9, 1);
INSERT INTO oys.sale_cartypecarmodel (car_model_id, transport_type_id) VALUES (10, 4);