INSERT INTO sale_bearingcapacity (id, bearing_capacity, premium, tag_value) VALUES (1, '3500 kq', 5, 1);
INSERT INTO sale_bearingcapacity (id, bearing_capacity, premium, tag_value) VALUES (2, '3500-7000 kq', 10, 2);
INSERT INTO sale_bearingcapacity (id, bearing_capacity, premium, tag_value) VALUES (3, '7000 kq и более', 15, 3);
INSERT INTO sale_carmanufacturer (id, name, tag_value) VALUES (1, 'Ford', 1);
INSERT INTO sale_carmanufacturer (id, name, tag_value) VALUES (2, 'Kia', 2);
INSERT INTO sale_carmanufacturer (id, name, tag_value) VALUES (3, 'Mercedes', 3);
INSERT INTO sale_carmanufacturer (id, name, tag_value) VALUES (4, 'Alfa Romeo', 4);
INSERT INTO sale_enginecapacity (id, engine_capacity, premium, tag_value) VALUES (1, '50-1500 sm3', 1, 1);
INSERT INTO sale_enginecapacity (id, engine_capacity, premium, tag_value) VALUES (2, '1501-2000 sm3', 2, 2);
INSERT INTO sale_enginecapacity (id, engine_capacity, premium, tag_value) VALUES (3, '2001-2500 sm3', 3, 3);
INSERT INTO sale_enginecapacity (id, engine_capacity, premium, tag_value) VALUES (4, '2501-3000 sm3', 4, 4);
INSERT INTO sale_enginecapacity (id, engine_capacity, premium, tag_value) VALUES (5, '3001-3500 sm3', 5, 5);
INSERT INTO sale_enginecapacity (id, engine_capacity, premium, tag_value) VALUES (6, '3501-4000 sm3', 6, 6);
INSERT INTO sale_enginecapacity (id, engine_capacity, premium, tag_value) VALUES (7, '4001-4500 sm3', 7, 7);
INSERT INTO sale_enginecapacity (id, engine_capacity, premium, tag_value) VALUES (8, '4501-5000 sm3', 8, 8);
INSERT INTO sale_enginecapacity (id, engine_capacity, premium, tag_value) VALUES (9, '>5000 sm3', 9, 9);
INSERT INTO sale_passengerseats (id, passenger_seats, premium, tag_value) VALUES (1, '9-16', 1, 1);
INSERT INTO sale_passengerseats (id, passenger_seats, premium, tag_value) VALUES (2, '16 и более', 2, 2);
INSERT INTO sale_persontype (id, person_type, premium, tag_value) VALUES (1, 'Физ. лицо', 1, 1);
INSERT INTO sale_persontype (id, person_type, premium, tag_value) VALUES (2, 'Юр. лицо', 2, 2);
INSERT INTO sale_transporttype (id, transport_type, premium, tag_value) VALUES (1, 'Легковые автомобили', 5, 1);
INSERT INTO sale_transporttype (id, transport_type, premium, tag_value) VALUES (2, 'Мотоцикл', 6, 2);
INSERT INTO sale_transporttype (id, transport_type, premium, tag_value) VALUES (3, 'Автобус и микроавтобусы', 5, 3);
INSERT INTO sale_transporttype (id, transport_type, premium, tag_value) VALUES (4, 'Грузовые автомобили', 6, 4);
INSERT INTO sale_transporttype (id, transport_type, premium, tag_value) VALUES (5, 'Прицепы и полуприцепы', 5, 5);
INSERT INTO sale_transporttype (id, transport_type, premium, tag_value) VALUES (6, 'Тракторы', 7, 6);
INSERT INTO sale_transporttype (id, transport_type, premium, tag_value) VALUES (7, 'Трамваи и троллейбусы', 5, 7);
INSERT INTO sale_cartype (id, name, tag_value) VALUES (1, 'Легковые автомобили', 1);
INSERT INTO sale_cartype (id, name, tag_value) VALUES (2, 'Мотоцикл', 2);
INSERT INTO sale_cartype (id, name, tag_value) VALUES (3, 'Автобус и микроавтобусы', 3);
INSERT INTO sale_cartype (id, name, tag_value) VALUES (4, 'Грузовые автомобили', 4);
INSERT INTO sale_cartype (id, name, tag_value) VALUES (5, 'Прицепы и полуприцепы', 5);
INSERT INTO sale_cartype (id, name, tag_value) VALUES (6, 'Тракторы', 6);
INSERT INTO sale_cartype (id, name, tag_value) VALUES (7, 'Трамваи и троллейбусы', 7);


