# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0002_auto_20150422_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, serialize=False, editable=False, primary_key=True)),
                ('d_create', models.DateTimeField(auto_now_add=True, verbose_name='creation date', db_index=True)),
                ('is_issued', models.BooleanField(default=False, verbose_name='issued', db_index=True, editable=False)),
                ('step', models.CharField(max_length=50, verbose_name='calculator step')),
                ('substep', models.CharField(max_length=50, verbose_name='calculator sub step')),
                ('layer', models.CharField(max_length=50, verbose_name='calculator layer')),
                ('main_product', models.PositiveSmallIntegerField(null=True, verbose_name='main product ID', blank=True)),
                ('main_product_text', models.CharField(max_length=100, null=True, verbose_name='main product title', blank=True)),
                ('d_start', models.DateField(verbose_name='contract start date')),
                ('term_insurance', models.PositiveSmallIntegerField(verbose_name='term insurance')),
                ('ins_person_pin', models.CharField(max_length=9, verbose_name='PIN')),
                ('ins_person_lname', models.CharField(max_length=50, verbose_name='last name')),
                ('ins_person_fname', models.CharField(max_length=50, verbose_name='first name')),
                ('ins_person_mname', models.CharField(max_length=50, verbose_name='middle name')),
                ('ins_person_gender', models.PositiveSmallIntegerField(verbose_name='gender')),
                ('ins_person_birthday', models.DateField(verbose_name='birthday')),
                ('ins_country', models.PositiveIntegerField(verbose_name='country')),
                ('ins_index', models.CharField(max_length=10, verbose_name='postal index (ZIP)')),
                ('ins_city', models.PositiveIntegerField(null=True, verbose_name='city', blank=True)),
                ('ins_city_custom', models.CharField(max_length=50, null=True, verbose_name='city (custom)', blank=True)),
                ('ins_address', models.CharField(max_length=70, null=True, verbose_name='address', blank=True)),
                ('ins_street', models.CharField(max_length=50, null=True, verbose_name='street', blank=True)),
                ('ins_house', models.CharField(max_length=10, null=True, verbose_name='house', blank=True)),
                ('ins_apartment', models.CharField(max_length=10, null=True, verbose_name='apartment', blank=True)),
                ('ins_phone', models.CharField(max_length=12, verbose_name='phone')),
                ('ins_email', models.EmailField(max_length=254, verbose_name='email')),
                ('delivery_type', models.CharField(max_length=10, verbose_name='delivery type')),
                ('delivery_date', models.DateField(null=True, verbose_name='delivery date', blank=True)),
                ('delivery_time', models.IntegerField(null=True, verbose_name='delivery time interval', blank=True)),
                ('delivery_city', models.PositiveIntegerField(null=True, verbose_name='city', blank=True)),
                ('delivery_street', models.CharField(max_length=50, null=True, verbose_name='street', blank=True)),
                ('delivery_house', models.CharField(max_length=10, null=True, verbose_name='house', blank=True)),
                ('delivery_apartment', models.CharField(max_length=10, null=True, verbose_name='apartment', blank=True)),
                ('delivery_phone', models.CharField(max_length=12, null=True, verbose_name='phone', blank=True)),
                ('delivery_comment', models.TextField(null=True, verbose_name='comments', blank=True)),
                ('delivery_takeout', models.IntegerField(null=True, verbose_name='takeout point', blank=True)),
                ('delivery_email', models.EmailField(max_length=254, null=True, verbose_name='delivery email', blank=True)),
                ('payment_type', models.CharField(max_length=10, null=True, verbose_name='payment type', blank=True)),
                ('p2_selected', models.BooleanField(default=False, verbose_name='product 2 selected')),
                ('p11_selected', models.BooleanField(default=False, verbose_name='product 11 selected')),
                ('p12_selected', models.BooleanField(default=False, verbose_name='product 12 selected')),
                ('auto_type', models.PositiveIntegerField(verbose_name='vehicle type')),
                ('auto_mark', models.PositiveIntegerField(verbose_name='vehicle mark')),
                ('auto_model', models.PositiveIntegerField(verbose_name='vehicle model')),
                ('auto_engine_capacity', models.PositiveIntegerField(null=True, verbose_name='vehicle engine capacity', blank=True)),
                ('auto_payload', models.PositiveIntegerField(null=True, verbose_name='vehicle payload', blank=True)),
                ('cnt_seats', models.PositiveIntegerField(null=True, verbose_name='vehicle seats', blank=True)),
                ('auto_createyear', models.PositiveIntegerField(null=True, verbose_name='vehicle creation year', blank=True)),
                ('auto_vin', models.CharField(max_length=17, null=True, verbose_name=b'VIN', blank=True)),
                ('auto_engine', models.CharField(max_length=17, null=True, verbose_name=b'EIN', blank=True)),
                ('auto_chassis', models.CharField(max_length=17, null=True, verbose_name=b'CIN', blank=True)),
                ('auto_number', models.CharField(max_length=12, verbose_name='vehicle registration number')),
                ('auto_region', models.PositiveIntegerField(verbose_name='vehicle registration region')),
                ('auto_cost', models.PositiveIntegerField(verbose_name='vehicle cost')),
                ('p11_inscompany', models.PositiveSmallIntegerField(null=True, verbose_name='insurance company', blank=True)),
                ('p11_sts_selection', models.CharField(max_length=50, null=True, verbose_name='station selection', blank=True)),
                ('p11_beneficiary', models.CharField(max_length=10, null=True, verbose_name='beneficiary', blank=True)),
                ('p11_bank_beneficiary', models.PositiveSmallIntegerField(null=True, verbose_name='bank', blank=True)),
                ('p12_inscompany', models.PositiveIntegerField(null=True, verbose_name='insurance company', blank=True)),
                ('p12_beneficiary', models.CharField(max_length=10, null=True, verbose_name='beneficiary', blank=True)),
                ('p12_bank_beneficiary', models.PositiveIntegerField(null=True, verbose_name='bank', blank=True)),
                ('p12_ins_sum', models.PositiveIntegerField(null=True, verbose_name='insurance sum', blank=True)),
                ('p12_acc_qty', models.PositiveIntegerField(null=True, verbose_name='accidents quantity', blank=True)),
                ('p12_evacuation', models.BooleanField(default=False, verbose_name='evacuation')),
                ('p12_cvi_extension_sum', models.PositiveIntegerField(null=True, verbose_name='cvi extension sum', blank=True)),
                ('p12_accident_ins_sum', models.PositiveIntegerField(null=True, verbose_name='accident insurance sum', blank=True)),
                ('p12_accident_ins_drivers', models.PositiveSmallIntegerField(null=True, verbose_name='accident insurance drivers', blank=True)),
                ('p12_additional_drivers', models.BooleanField(default=False, verbose_name='additional drivers')),
                ('p12_additional_driver_2', models.BooleanField(default=False, verbose_name='second additional driver')),
                ('ins_owner', models.BooleanField(default=True, verbose_name='insurant is vehicle owner')),
                ('owner_pin', models.CharField(max_length=9, verbose_name='PIN')),
                ('owner_lname', models.CharField(max_length=50, verbose_name='last name')),
                ('owner_fname', models.CharField(max_length=50, verbose_name='first name')),
                ('owner_mname', models.CharField(max_length=50, verbose_name='middle name')),
                ('owner_gender', models.PositiveSmallIntegerField(verbose_name='gender')),
                ('owner_birthday', models.DateField(verbose_name='birthday')),
                ('owner_country', models.PositiveIntegerField(verbose_name='country')),
                ('owner_index', models.CharField(max_length=10, verbose_name='postal index (ZIP)')),
                ('owner_city', models.PositiveIntegerField(null=True, verbose_name='city', blank=True)),
                ('owner_city_custom', models.CharField(max_length=50, null=True, verbose_name='city (custom)', blank=True)),
                ('owner_address', models.CharField(max_length=70, null=True, verbose_name='address', blank=True)),
                ('owner_street', models.CharField(max_length=50, null=True, verbose_name='street', blank=True)),
                ('owner_house', models.CharField(max_length=10, null=True, verbose_name='house', blank=True)),
                ('owner_apartment', models.CharField(max_length=10, null=True, verbose_name='apartment', blank=True)),
                ('owner_phone', models.CharField(max_length=12, verbose_name='phone')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='email')),
                ('ad1_pin', models.CharField(max_length=9, verbose_name='PIN')),
                ('ad1_lname', models.CharField(max_length=50, verbose_name='last name')),
                ('ad1_fname', models.CharField(max_length=50, verbose_name='first name')),
                ('ad1_mname', models.CharField(max_length=50, verbose_name='middle name')),
                ('ad1_gender', models.PositiveSmallIntegerField(verbose_name='gender')),
                ('ad1_birthday', models.DateField(verbose_name='birthday')),
                ('ad1_country', models.PositiveIntegerField(verbose_name='country')),
                ('ad1_index', models.CharField(max_length=10, verbose_name='postal index (ZIP)')),
                ('ad1_city', models.PositiveIntegerField(null=True, verbose_name='city', blank=True)),
                ('ad1_city_custom', models.CharField(max_length=50, null=True, verbose_name='city (custom)', blank=True)),
                ('ad1_address', models.CharField(max_length=70, null=True, verbose_name='address', blank=True)),
                ('ad1_street', models.CharField(max_length=50, null=True, verbose_name='street', blank=True)),
                ('ad1_house', models.CharField(max_length=10, null=True, verbose_name='house', blank=True)),
                ('ad1_apartment', models.CharField(max_length=10, null=True, verbose_name='apartment', blank=True)),
                ('ad1_phone', models.CharField(max_length=12, verbose_name='phone')),
                ('ad1_email', models.EmailField(max_length=254, verbose_name='email')),
                ('ad2_pin', models.CharField(max_length=9, verbose_name='PIN')),
                ('ad2_lname', models.CharField(max_length=50, verbose_name='last name')),
                ('ad2_fname', models.CharField(max_length=50, verbose_name='first name')),
                ('ad2_mname', models.CharField(max_length=50, verbose_name='middle name')),
                ('ad2_gender', models.PositiveSmallIntegerField(verbose_name='gender')),
                ('ad2_birthday', models.DateField(verbose_name='birthday')),
                ('ad2_country', models.PositiveIntegerField(verbose_name='country')),
                ('ad2_index', models.CharField(max_length=10, verbose_name='postal index (ZIP)')),
                ('ad2_city', models.PositiveIntegerField(null=True, verbose_name='city', blank=True)),
                ('ad2_city_custom', models.CharField(max_length=50, null=True, verbose_name='city (custom)', blank=True)),
                ('ad2_address', models.CharField(max_length=70, null=True, verbose_name='address', blank=True)),
                ('ad2_street', models.CharField(max_length=50, null=True, verbose_name='street', blank=True)),
                ('ad2_house', models.CharField(max_length=10, null=True, verbose_name='house', blank=True)),
                ('ad2_apartment', models.CharField(max_length=10, null=True, verbose_name='apartment', blank=True)),
                ('ad2_phone', models.CharField(max_length=12, verbose_name='phone')),
                ('ad2_email', models.EmailField(max_length=254, verbose_name='email')),
                ('client', models.ForeignKey(blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='client')),
            ],
            options={
                'verbose_name': 'vehicle contract',
                'verbose_name_plural': 'vehicle contracts',
            },
        ),
        migrations.RemoveField(
            model_name='cvicontract',
            name='client',
        ),
        migrations.DeleteModel(
            name='CVIContract',
        ),
    ]
